[package]
name = "image-fryer"
author = ["Rhelvetican"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
image = "0"
imageproc = "0"
anyhow = "1"
gcd = "2"
